// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-etcd-lock/lock (interfaces: RWLocker)

// Package lockmock is a generated GoMock package.
package lockmock

import (
	reflect "reflect"

	lock "github.com/Scalingo/go-etcd-lock/v5/lock"
	gomock "github.com/golang/mock/gomock"
)

// MockRWLocker is a mock of RWLocker interface.
type MockRWLocker struct {
	ctrl     *gomock.Controller
	recorder *MockRWLockerMockRecorder
}

// MockRWLockerMockRecorder is the mock recorder for MockRWLocker.
type MockRWLockerMockRecorder struct {
	mock *MockRWLocker
}

// NewMockRWLocker creates a new mock instance.
func NewMockRWLocker(ctrl *gomock.Controller) *MockRWLocker {
	mock := &MockRWLocker{ctrl: ctrl}
	mock.recorder = &MockRWLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRWLocker) EXPECT() *MockRWLockerMockRecorder {
	return m.recorder
}

// AcquireRead mocks base method.
func (m *MockRWLocker) AcquireRead(arg0 string, arg1 int) (lock.Lock, error) {
	ret := m.ctrl.Call(m, "AcquireRead", arg0, arg1)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireRead indicates an expected call of AcquireRead.
func (mr *MockRWLockerMockRecorder) AcquireRead(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireRead", reflect.TypeOf((*MockRWLocker)(nil).AcquireRead), arg0, arg1)
}

// WaitAcquireRead mocks base method.
func (m *MockRWLocker) WaitAcquireRead(arg0 string, arg1 int) (lock.Lock, error) {
	ret := m.ctrl.Call(m, "WaitAcquireRead", arg0, arg1)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireRead indicates an expected call of WaitAcquireRead.
func (mr *MockRWLockerMockRecorder) WaitAcquireRead(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireRead", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireRead), arg0, arg1)
}

// AcquireWrite mocks base method.
func (m *MockRWLocker) AcquireWrite(arg0 string, arg1 int) (lock.Lock, error) {
	ret := m.ctrl.Call(m, "AcquireWrite", arg0, arg1)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireWrite indicates an expected call of AcquireWrite.
func (mr *MockRWLockerMockRecorder) AcquireWrite(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireWrite", reflect.TypeOf((*MockRWLocker)(nil).AcquireWrite), arg0, arg1)
}

// WaitAcquireWrite mocks base method.
func (m *MockRWLocker) WaitAcquireWrite(arg0 string, arg1 int) (lock.Lock, error) {
	ret := m.ctrl.Call(m, "WaitAcquireWrite", arg0, arg1)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireWrite indicates an expected call of WaitAcquireWrite.
func (mr *MockRWLockerMockRecorder) WaitAcquireWrite(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireWrite", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireWrite), arg0, arg1)
}

// Wait mocks base method.
func (m *MockRWLocker) Wait(arg0 string) error {
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockRWLockerMockRecorder) Wait(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRWLocker)(nil).Wait), arg0)
}
