// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-etcd-lock/v5/lock (interfaces: Locker)

// Package lockmock is a generated GoMock package.
package lockmock

import (
	context "context"
	reflect "reflect"

	lock "github.com/Scalingo/go-etcd-lock/v5/lock"
	gomock "go.uber.org/mock/gomock"
)

// MockLocker is a mock of Locker interface.
type MockLocker struct {
	ctrl     *gomock.Controller
	recorder *MockLockerMockRecorder
	isgomock struct{}
}

// MockLockerMockRecorder is the mock recorder for MockLocker.
type MockLockerMockRecorder struct {
	mock *MockLocker
}

// NewMockLocker creates a new mock instance.
func NewMockLocker(ctrl *gomock.Controller) *MockLocker {
	mock := &MockLocker{ctrl: ctrl}
	mock.recorder = &MockLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocker) EXPECT() *MockLockerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLocker) Acquire(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLockerMockRecorder) Acquire(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLocker)(nil).Acquire), key, ttl)
}

// AcquireWithContext mocks base method.
func (m *MockLocker) AcquireWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireWithContext indicates an expected call of AcquireWithContext.
func (mr *MockLockerMockRecorder) AcquireWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireWithContext", reflect.TypeOf((*MockLocker)(nil).AcquireWithContext), ctx, key, ttl)
}

// Wait mocks base method.
func (m *MockLocker) Wait(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockLockerMockRecorder) Wait(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockLocker)(nil).Wait), key)
}

// WaitAcquire mocks base method.
func (m *MockLocker) WaitAcquire(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquire", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquire indicates an expected call of WaitAcquire.
func (mr *MockLockerMockRecorder) WaitAcquire(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquire", reflect.TypeOf((*MockLocker)(nil).WaitAcquire), key, ttl)
}

// WaitAcquireWithContext mocks base method.
func (m *MockLocker) WaitAcquireWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquireWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireWithContext indicates an expected call of WaitAcquireWithContext.
func (mr *MockLockerMockRecorder) WaitAcquireWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireWithContext", reflect.TypeOf((*MockLocker)(nil).WaitAcquireWithContext), ctx, key, ttl)
}

// WaitWithContext mocks base method.
func (m *MockLocker) WaitWithContext(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitWithContext", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitWithContext indicates an expected call of WaitWithContext.
func (mr *MockLockerMockRecorder) WaitWithContext(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitWithContext", reflect.TypeOf((*MockLocker)(nil).WaitWithContext), ctx, key)
}
