// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-etcd-lock/v5/lock (interfaces: RWLocker)

// Package lockmock is a generated GoMock package.
package lockmock

import (
	context "context"
	reflect "reflect"

	lock "github.com/Scalingo/go-etcd-lock/v5/lock"
	gomock "go.uber.org/mock/gomock"
)

// MockRWLocker is a mock of RWLocker interface.
type MockRWLocker struct {
	ctrl     *gomock.Controller
	recorder *MockRWLockerMockRecorder
	isgomock struct{}
}

// MockRWLockerMockRecorder is the mock recorder for MockRWLocker.
type MockRWLockerMockRecorder struct {
	mock *MockRWLocker
}

// NewMockRWLocker creates a new mock instance.
func NewMockRWLocker(ctrl *gomock.Controller) *MockRWLocker {
	mock := &MockRWLocker{ctrl: ctrl}
	mock.recorder = &MockRWLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRWLocker) EXPECT() *MockRWLockerMockRecorder {
	return m.recorder
}

// AcquireRead mocks base method.
func (m *MockRWLocker) AcquireRead(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireRead", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireRead indicates an expected call of AcquireRead.
func (mr *MockRWLockerMockRecorder) AcquireRead(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireRead", reflect.TypeOf((*MockRWLocker)(nil).AcquireRead), key, ttl)
}

// AcquireReadWithContext mocks base method.
func (m *MockRWLocker) AcquireReadWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireReadWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireReadWithContext indicates an expected call of AcquireReadWithContext.
func (mr *MockRWLockerMockRecorder) AcquireReadWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireReadWithContext", reflect.TypeOf((*MockRWLocker)(nil).AcquireReadWithContext), ctx, key, ttl)
}

// AcquireWrite mocks base method.
func (m *MockRWLocker) AcquireWrite(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireWrite", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireWrite indicates an expected call of AcquireWrite.
func (mr *MockRWLockerMockRecorder) AcquireWrite(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireWrite", reflect.TypeOf((*MockRWLocker)(nil).AcquireWrite), key, ttl)
}

// AcquireWriteWithContext mocks base method.
func (m *MockRWLocker) AcquireWriteWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireWriteWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireWriteWithContext indicates an expected call of AcquireWriteWithContext.
func (mr *MockRWLockerMockRecorder) AcquireWriteWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireWriteWithContext", reflect.TypeOf((*MockRWLocker)(nil).AcquireWriteWithContext), ctx, key, ttl)
}

// Wait mocks base method.
func (m *MockRWLocker) Wait(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockRWLockerMockRecorder) Wait(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRWLocker)(nil).Wait), key)
}

// WaitAcquireRead mocks base method.
func (m *MockRWLocker) WaitAcquireRead(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquireRead", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireRead indicates an expected call of WaitAcquireRead.
func (mr *MockRWLockerMockRecorder) WaitAcquireRead(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireRead", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireRead), key, ttl)
}

// WaitAcquireReadWithContext mocks base method.
func (m *MockRWLocker) WaitAcquireReadWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquireReadWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireReadWithContext indicates an expected call of WaitAcquireReadWithContext.
func (mr *MockRWLockerMockRecorder) WaitAcquireReadWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireReadWithContext", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireReadWithContext), ctx, key, ttl)
}

// WaitAcquireWrite mocks base method.
func (m *MockRWLocker) WaitAcquireWrite(key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquireWrite", key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireWrite indicates an expected call of WaitAcquireWrite.
func (mr *MockRWLockerMockRecorder) WaitAcquireWrite(key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireWrite", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireWrite), key, ttl)
}

// WaitAcquireWriteWithContext mocks base method.
func (m *MockRWLocker) WaitAcquireWriteWithContext(ctx context.Context, key string, ttl int) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitAcquireWriteWithContext", ctx, key, ttl)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitAcquireWriteWithContext indicates an expected call of WaitAcquireWriteWithContext.
func (mr *MockRWLockerMockRecorder) WaitAcquireWriteWithContext(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitAcquireWriteWithContext", reflect.TypeOf((*MockRWLocker)(nil).WaitAcquireWriteWithContext), ctx, key, ttl)
}
